--- 
title: "Introducción al uso de machine learning en biología"
author: "Jhan C. Salazar y Cristian Román-Palacios"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Una introducción breve a Machine Learning

El machine learning es una de las herramientas que más se aplica en diferentes partes de nuestra vida diaria (Poner algunos ejemplos). Sin embargo, muy poca gente sabe cómo utilizar ya sea por miedo o desconocimiento a la programación, o simplemente, porque mucha de la información se encuentra en otro idioma, usualmente en inglés. Con este libro, buscamos dar una breve introducción al machine learning y su aplicación en el idioma español. Aunque los ejemplos que vamos a utilizar a lo largo del libro son en un contexto biológico, esto no significa que no puedan ser aplicados a otras áreas de estudio. Este libro va dirigido a todas las personas que quieren aprender a usar machine learning en su investigaciones, que estén en diferentes niveles de su formación académica o que trabajen en la indrustria, ya sea que tengan o no conocimiento previo en programación. El foco principal de este libro no es sólo enseñar cómo utilizar y entender qué es machine learning, si no hacer accesible su uso para personas de habla hispana.

Este libro sigue una estructura que inicia desde la introduccion a machine learning, pasa por regresiones lineales, aspectos de clasificacion, y termina con introducciones cortas a modelos de regresion y clasificacion un poco mas complejos. Cada uno de los capitulos revisa tando el componente practico como el teorico del tema principal a tratar. Primero, la discusion teorica incluye detalles generales sobre la fundamentacion de algoritmos y su uso en diferentes contextos. Segundo, la implementacion practica incluye estudios de casos basados en publicaciones recientes. En general, la consulta de este libro implicara una exposicion a aspectos generales tanto de machine learning en su teoria y practica, asi como tambien a su implementacion directa en el analisis de datos biologicos.

Como se ha mencionado anteriormente el enfoque de este libro es aprender a usar las herramientas que machine learning provee para resolver problemas o responder preguntar en biología. Sin embargo, aún no hemos dado una definición de los que es machine learning. En pocas palabras, machine learning se refiere al uso de analisis estadísticos para hacer predicciones o inferencias sobre un problema en particular. 

Aunque no nos demos cuenta el machine learning hace parte de nuestro día a día. Cuando usamos la cámara de nuestros celulares para desbloquear usando nuestra cara, cuando utilizamos un filtro al momento de tomarnos una foto o cuando nuestro correo envía algunos mensajes a la carpeta de no deseados (SPAM), estamos usando machine learning. 

Existe una variedad de lenguajes de programacion que permiten implementar algoritmos de machine learning. En general, el componente practico de este libro estara enfocado en ilustrar el uso de esta perspectiva analitica utilizando el lenguaje de programacion `R`. Esta herramientaes de codigo abierto, gratuita, y tiene asociado una comunidad amplia red de usuarios y desarrolladores que se encuentran en constante interaccion. Como alternativa `R` estan `python`, `julia`, `matlab`, entre otros lenguages que permiten tambien el analisis de datos en una aproximacion de machine learning. El codigo que se presenta en este documento puede ser traducido a estos lenguajes. Sin embargo, para quienes consultan el libro y no tienen experiencia en programacion en `R`, el primer capitulo se enfoca en introducir `R` como el lenguaje para usos subsecuentes en los componentes practicos del documento.

Ademas de nuestro libro, existen diferentes recursos en español que tratan diferentes aspectos de machine learning en `R` y otros languajes de programación. Por ejemplo, en su [libro](http://rafalab.dfci.harvard.edu/dslibro/), Rafael A. Irizarry da una breve introduccion a `R` en el contexto de ciencia de datos. [R Para ciencia de datos](http://es.r4ds.hadley.nz/), traducido del ingles, tambien es un excelente recurso introductorio tanto a `R` como a machine learning. Aunque estos recursos (y otros) se enuentran en español, los documentos existentes son (1) traducciones literales a textos originalmente escritos en ingles, (2) tienen poco enfasis en machine learning por ser pensados en el contexto de data science, o (3) no tienen una aplicacion directa en biologia. Por lo tanto, con este documento propendemos a integrar aspectos basicos de machine learning en el contexto actual de biologia latinoamericana, mientras resaltamos el trabajo investigativo en la region.